CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    token TEXT,
    poin INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
